Fix error message about rubocop-rspec_rails
Was getting this message, it looks like we need require the rspec rails
cops seperatly:

Error: `RSpec/Rails` cops have been extracted to the `rubocop-rspec_rails` gem.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-mynewsdesk-mnd-rubocop-master--rubocop-yml, please update it)